quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Password09
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:54325/postgres?currentSchema=crudibli_schema

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# turn on CORS support?
quarkus.http.cors=true

# allow any origin (including different ports)
quarkus.http.cors.origins=*

# allow these HTTP methods
quarkus.http.cors.methods=GET,HEAD,POST,PUT,DELETE,OPTIONS

# allow client to send these headers
quarkus.http.cors.headers=origin,content-type,accept,authorization

# if you need cookies/auth credentials
quarkus.http.cors.access-control-allow-credentials=true

# expose any other headers back to the client
quarkus.http.cors.exposed-headers=*

